title: Document Compression Add-On 
description: Compresses a document that is already uploaded to DocumentCloud and uploads a copy. 
instructions: ''
type: object
documents:
  [selected]
properties:
  project_id:
    title: Project ID
    type: integer
    description: Project ID of the project you would like to upload the documents to. 
  access_level:
    title: Access level for uploaded documents
    type: string
    default: private
    enum:
      - private
      - organization
      - public
categories:
  - file
